---
# - user:
#     name: vegamite

# - user:
#     name: docker

- name: Add deploy user
  become: true
  user:
    name: deploy
    groups: docker
    home: "{{ ansible_env.APPLICATION_HOME }}"

- name: Install Python 2.7
  become: true
  apt:
    name: python2.7
    state: latest
    update_cache: yes

- name: Open permissions for site-packages
  file:
    path: "{{ ansible_env.PYTHONPATH }}"
    mode: ugo+rx

# - name: Set python to python 2.7

- name: Install pip
  # become: true
  apt:
    name: python-pip
    state: latest

# - name: Install pip for deploy user
#   become: true
#   become_user: deploy
#   apt:
#     name: python-pip
#     state: latest

# - name: Link pip3 to pip
#   become: true
#   file:
#     src: /usr/bin/pip3
#     dest: /usr/bin/pip
#     state: link

- name: Install docker-py
  pip: 
    name: docker-py