---
# - user:
#     name: vegamite

# - user:
#     name: docker

- name: Add deploy user
  become: true
  user:
    name: deploy
    groups: docker,deploy
    home: "{{ ansible_env.APPLICATION_HOME }}"

- name: Configure app home permissions
  become: true
  file:
    path: "{{ ansible_env.APPLICATION_HOME }}"
    state: directory
    owner: deploy
    group: docker
    mode: 0755

- name: Set environment
  become: true
  become_user: deploy
  lineinfile:
    path: "{{ ansible_env.APPLICATION_HOME }}/.profile"
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - "export APP_HOME={{ ansible_env.APPLICATION_HOME }}"

- name: "Install Python 2.7, 3 and virtualenv, rabbitmq"
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - python2.7
    - python3
    - python3-venv
    - rabbitmq-server
    - python-pip

- name: Open permissions for site-packages
  file:
    path: "{{ ansible_env.PYTHONPATH }}"
    mode: ugo+rx

- name: Install docker-py
  pip:
    name: docker-py
    umask: "0022"
    extra_args: --force-reinstall
  become: True





