---
# - user:
#     name: vegamite

# - user:
#     name: docker

- name: Add deploy user
  become: true
  user:
    name: deploy
    groups: docker
    home: "{{ ansible_env.APPLICATION_HOME }}"

- name: Configure app home permissions
  become: true
  file:
    path: "{{ ansible_env.APPLICATION_HOME }}"
    state: directory
    owner: deploy
    group: docker
    mode: 0755

- name: "Install Python 2.7, 3 and virtualenv"
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - python2.7
    - python3
    - python3-venv

- name: Open permissions for site-packages
  file:
    path: "{{ ansible_env.PYTHONPATH }}"
    mode: ugo+rx

# - name: Set python to python 2.7

- name: Install pip
  become: true
  apt:
    name: python-pip
    state: latest
    update_cache: yes


# - name: Install pip for deploy user
#   become: true
#   become_user: deploy
#   apt:
#     name: python-pip
#     state: latest

# - name: Link pip3 to pip
#   become: true
#   file:
#     src: /usr/bin/pip3
#     dest: /usr/bin/pip
#     state: link

- name: Install docker-py
  pip:
    name: docker-py
    umask: "0022"
    extra_args: --force-reinstall
  become: True



