---
- name: Add docker remote key
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Ensure docker registry is available
  become: true
  apt_repository: repo='deb https://download.docker.com/linux/ubuntu xenial stable' state=present

- name: ensure docker and dependencies are installed
  become: true
  apt: name=docker-ce update_cache=yes

- name: Restart docker service
  become: true
  service:
    name: docker 
    state: restarted

# - name: Pull containers
#   become: true
#   # become_user: deploy
#   docker_image:
#     name: "{{ item.name }}"
#   with_items:
#   - { name: mysql }
#   - { name: influxdb }
#   - { name: redis }



