---
- include_vars:
    file: vars/git_private_key.yaml

- set_fact:
    celery_bin_path: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}/bin/celery"
    vegamite_app: "vegamite.tasks"
    celery_app_path: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}/vegamite"
    logging_path: "{{ ansible_env.APPLICATION_HOME }}/logs/vegamite"
    pid_path: "{{ ansible_env.APPLICATION_HOME }}/pid/vegamite"
    celery_user: deploy
    celery_group: deploy
    celery_opts: "-B"

- name: Set environment
  become: true
  become_user: deploy
  lineinfile:
    path: "{{ ansible_env.APPLICATION_HOME }}/.profile"
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - "export VEGAMITE_HOME={{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}"
    - "export VEGAMITE_DATA={{ ansible_env.APPLICATION_HOME }}/volumes/vegamite/data"

- name: Setup vegamite virtualenv
  become: true
  become_user: deploy
  command: "python3 -m venv {{ ansible_env.APPLICATION_HOME }}/vega-env"

- name: ensure github.com is a known host
  become: true
  become_user: deploy
  lineinfile:
    dest: "{{ ansible_env.APPLICATION_HOME }}/.ssh/known_hosts"
    state: present
    create: yes
    regexp: "^github\\.com"
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

- name: Copy encrypted private key
  become: true
  become_user: deploy
  copy:
    content: "{{ key }}"
    dest: "{{ ansible_env.APPLICATION_HOME }}/.ssh/{{ privatekey_name }}"
    mode: 0600

- name: Clone git repository
  become: true
  become_user: deploy
  git:
    repo: '{{ github_repo }}'
    dest: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}/vegamite"
    key_file: "~/.ssh/{{ privatekey_name }}"
    accept_hostkey: yes
    version: development

- name: Install vegamite into virtualenv
  become: true
  become_user: deploy
  pip:
    virtualenv_python: python3
    virtualenv: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}/"
    chdir: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}/vegamite"
    # name: "{{ ansible_env.APPLICATION_HOME }}/vega-env/vegamite"
    requirements: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}/vegamite/requirements.txt"
    extra_args: "--upgrade"

- name: "Ensure {{ ansible_env.APPLICATION_HOME }}/conf/vegamite/ dir exists"
  become: true
  become_user: deploy
  file: 
    path: "{{ vegamite_config_dir }}" 
    state: directory

- name: Copy vegamite configuration file
  become: true
  become_user: deploy
  template:
    src: settings.j2
    dest: "{{ vegamite_config_dir }}/settings.yaml"
    mode: 0600

- name: Initialize mysql database with vegamite schema and data
  become: true
  become_user: deploy
  shell: "source ~/.profile && source bin/activate && python vegamite/scripts/setup_database.py"
  args:
    chdir: "{{ ansible_env.APPLICATION_HOME }}/{{ virtualenv_name }}"
    executable: /bin/bash


- name: Celery daemon script
  become: true
  template:
    src: celeryd.j2
    dest: "/etc/default/celeryd"

- name: Start celery daemon
  become: true
  shell: "serive start celeryd"







