---
- hosts: production
  environment:
    APPLICATION_HOME: "/app"
    APP_HOME: "/app"
  user: ubuntu
  vars:
    username: ubuntu
    initialize_database: false
  roles:
    - common
    - vegamite