---
- hosts: production
  environment:
    PYTHONPATH: "/home/ubuntu/.local/lib/python2.7/site-packages"
    APPLICATION_HOME: "/app"
    APP_HOME: "/app"
  user: ubuntu
  vars:
    username: ubuntu
    initialize_database: true
    initial_exchanges: "gdax"
  roles:
    - common
    - docker
    - mysql
    - influxdb
    - grafana
    - redis
    - vegamite
