---
- name: Ensure influxdb dirs exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: deploy
    group: docker
    mode: 0755
    recurse: yes
  with_items:
    - "{{ influxdb_conf_dir }}"
    - "{{ influxdb_lib_dir }}"

- name: Run influxdb server
  become: true
  become_user: deploy
  docker_container:
    env:
      # MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      PYTHONPATH: "{{ ansible_env.PYTHONPATH }}"
    image: influxdb
    name: "{{ influxdb_container_name }}"
    ports:
      - "{{ influxdb_port }}:8086"
    pull: true
    recreate: true
    restart_policy: always
    state: "{{ influxdb_state }}"
    volumes:
      - "{{ influxdb_conf_dir }}:/etc/influxdb"
      - "{{ influxdb_lib_dir }}:/var/lib/influxdb"
