---
- name: Ensure influxdb dirs exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: deploy
    group: docker
    mode: 0775
    recurse: yes
  with_items:
    - "{{ influxdb_conf_dir }}"
    - "{{ influxdb_lib_dir }}"

- name: Copy influx configuration file
  become: true
  become_user: deploy
  template:
    src: influxdb_config.j2
    dest: "{{ influxdb_conf_dir }}/influxdb.conf"
    mode: 0755

- name: Run influxdb server
  become: true
  become_user: deploy
  docker_container:
    env:
      # MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      PYTHONPATH: "{{ ansible_env.PYTHONPATH }}"
    image: influxdb
    name: "{{ influxdb_container_name }}"
    ports:
      - "{{ influxdb_port }}:8086"
    pull: true
    recreate: true
    restart_policy: always
    state: "{{ influxdb_state }}"
    volumes:
      - "{{ influxdb_conf_dir }}:/etc/influxdb:ro"
      - "{{ influxdb_lib_dir }}:/var/lib/influxdb:rw"
    log_driver: json-file
    log_opt:
      max-size: "100m"